# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20160301_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainblock',
            name='link',
            field=models.CharField(choices=[('SV', 'Services'), ('PF', 'Portfolio')], default=datetime.datetime(2016, 3, 1, 14, 13, 45, 784817, tzinfo=utc), max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainblock',
            name='photo',
            field=models.ImageField(default=datetime.datetime(2016, 3, 1, 14, 14, 4, 799782, tzinfo=utc), upload_to='photos', verbose_name='Home Picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolioblock',
            name='photo',
            field=models.ImageField(default=datetime.datetime(2016, 3, 1, 14, 14, 14, 493854, tzinfo=utc), upload_to='photos', verbose_name='Portfolio Picture'),
            preserve_default=False,
        ),
    ]
