# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20160301_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutblock',
            name='pic',
            field=models.CharField(blank=True, max_length=30, verbose_name='About Pic'),
        ),
        migrations.AlterField(
            model_name='mainblock',
            name='link',
            field=models.CharField(blank=True, choices=[('SV', 'Services'), ('PF', 'Portfolio')], max_length=2),
        ),
        migrations.AlterField(
            model_name='mainblock',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Home Picture'),
        ),
        migrations.AlterField(
            model_name='portfolioblock',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Portfolio Picture'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='pic',
            field=models.CharField(blank=True, max_length=30, verbose_name='Services Pic'),
        ),
    ]
