# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20160301_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=30, verbose_name='Shop Name')),
                ('services', models.CharField(max_length=30, verbose_name='Our Services')),
                ('portfolio', models.CharField(max_length=30, verbose_name='Our Portfolio')),
                ('aboutus', models.CharField(max_length=30, verbose_name='About Us')),
            ],
        ),
        migrations.DeleteModel(
            name='MainBlock',
        ),
        migrations.AddField(
            model_name='homeblock',
            name='link',
            field=models.CharField(blank=True, choices=[('SV', 'Services'), ('PF', 'Portfolio')], max_length=2),
        ),
        migrations.AddField(
            model_name='homeblock',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Home Picture'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='pic',
            field=models.CharField(max_length=30, verbose_name='About Pic'),
        ),
    ]
