# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20160301_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeblock',
            name='link',
        ),
    ]
