# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_remove_homeblock_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutblock',
            options={'ordering': ['-sequence_num']},
        ),
        migrations.AlterModelOptions(
            name='portfolioblock',
            options={'ordering': ['-sequence_num']},
        ),
        migrations.AlterModelOptions(
            name='servicesblock',
            options={'ordering': ['-sequence_num']},
        ),
        migrations.RemoveField(
            model_name='aboutblock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolioblock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicesblock',
            name='created_at',
        ),
        migrations.AddField(
            model_name='aboutblock',
            name='sequence_num',
            field=models.IntegerField(blank=True, default=1, help_text='數字越小此篇介紹放越前面', verbose_name='About Sequence'),
        ),
        migrations.AddField(
            model_name='portfolioblock',
            name='sequence_num',
            field=models.IntegerField(blank=True, default=1, help_text='請輸入1~8, 數字越小此篇介紹放越前面', verbose_name='Portfolio Sequence'),
        ),
        migrations.AddField(
            model_name='servicesblock',
            name='sequence_num',
            field=models.IntegerField(blank=True, default=1, help_text='請輸入1~8, 數字越小此篇介紹放越前面', verbose_name='Services Sequence'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='pic',
            field=models.CharField(help_text='請輸入', max_length=30, verbose_name='About Pic'),
        ),
        migrations.AlterField(
            model_name='homeblock',
            name='subtitle',
            field=models.CharField(help_text='商店介紹', max_length=100, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='navblock',
            name='shopname',
            field=models.CharField(help_text='商店的名字', max_length=30, verbose_name='Shop Name'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='pic',
            field=models.CharField(blank=True, help_text='請在 ', max_length=30, verbose_name='Services Pic'),
        ),
    ]
