# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20160302_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutblock',
            name='shop_mail',
            field=models.CharField(default=1, help_text='公司的 mail', max_length=254, verbose_name='Official E-mail'),
        ),
    ]
