# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_aboutblock_shop_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutblock',
            name='content',
            field=models.CharField(default=None, max_length=100, verbose_name='About Content'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='pic',
            field=models.CharField(default=None, help_text='請輸入', max_length=30, verbose_name='About Pic'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='sequence_num',
            field=models.IntegerField(default=1, help_text='數字越小此篇介紹放越前面', verbose_name='About Sequence'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='shop_mail',
            field=models.EmailField(default=None, help_text='公司的 mail', max_length=254, verbose_name='Official E-mail'),
        ),
        migrations.AlterField(
            model_name='aboutblock',
            name='title',
            field=models.CharField(default=None, max_length=30, verbose_name='About Title'),
        ),
        migrations.AlterField(
            model_name='homeblock',
            name='subtitle',
            field=models.CharField(default=None, help_text='商店介紹', max_length=100, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='homeblock',
            name='title',
            field=models.CharField(default=None, max_length=100, verbose_name='Main Title'),
        ),
        migrations.AlterField(
            model_name='navblock',
            name='aboutus',
            field=models.CharField(default=None, max_length=30, verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='navblock',
            name='services',
            field=models.CharField(default=None, max_length=30, verbose_name='Our Services'),
        ),
        migrations.AlterField(
            model_name='navblock',
            name='shopname',
            field=models.CharField(default=None, help_text='商店的名字', max_length=30, verbose_name='Shop Name'),
        ),
        migrations.AlterField(
            model_name='portfolioblock',
            name='sequence_num',
            field=models.IntegerField(default=1, help_text='請輸入1~8, 數字越小此篇介紹放越前面', verbose_name='Portfolio Sequence'),
        ),
        migrations.AlterField(
            model_name='portfolioblock',
            name='tag',
            field=models.CharField(default=None, max_length=30, verbose_name='Portfolio tag'),
        ),
        migrations.AlterField(
            model_name='portfolioblock',
            name='title',
            field=models.CharField(default=None, max_length=30, verbose_name='Portfolio name'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='content',
            field=models.CharField(default=None, max_length=100, verbose_name='Services Content'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='pic',
            field=models.CharField(default=None, help_text='請在 ', max_length=30, verbose_name='Services Pic'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='sequence_num',
            field=models.IntegerField(default=1, help_text='請輸入1~8, 數字越小此篇介紹放越前面', verbose_name='Services Sequence'),
        ),
        migrations.AlterField(
            model_name='servicesblock',
            name='title',
            field=models.CharField(default=None, max_length=30, verbose_name='Services Title'),
        ),
    ]
