# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_name', models.CharField(max_length=100, verbose_name='Name')),
                ('msg_email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='E-mail')),
                ('msg_content', models.TextField(help_text='Leave us a message.', max_length=500, verbose_name='Message')),
                ('msg_created_at', models.DateTimeField(auto_now_add=True, verbose_name='DateTime')),
            ],
            options={
                'ordering': ['-msg_created_at'],
            },
        ),
    ]
