# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavemessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='leavemessage',
            old_name='msg_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='leavemessage',
            old_name='msg_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='leavemessage',
            old_name='msg_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='leavemessage',
            old_name='msg_name',
            new_name='name',
        ),
    ]
